ALTER TABLE FoodOrders MODIFY COLUMN OrderID INT PRIMARY KEY, MODIFY Quantity INT NOT NULL, MODIFY Cost DECIMAL(4,2) NOT NULL;
ALTER TABLE FoodOrders ADD COLUMN OrderDate DATE NOT NULL, add column CustomerID INT NOT NULL;
ALTER TABLE FoodOrders ADD FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID);
ALTER TABLE FoodOrders DROP COLUMN OrderDate;
ALTER TABLE FoodOrders RENAME COLUMN Cost TO Total;
