ALTER TABLE Staff2 MODIFY COLUMN staffID INT NOT NULL PRIMARY KEY, MODIFY COLUMN fullName VARCHAR(100) NOT NULL, MODIFY COLUMN phoneNumber INT NOT NULL;
ALTER TABLE Staff2 ADD COLUMN Role VARCHAR(50) NOT NULL;
ALTER TABLE Staff2 DROP COLUMN phoneNumber;
