CREATE DATABASE IF NOT EXISTS luckyshrub_db;
USE luckyshrub_db;

CREATE TABLE IF NOT EXISTS Clients(ClientID CHAR(5) NOT NULL PRIMARY KEY, FullName VARCHAR(100), ContactNumber INT, Address VARCHAR(200));

CREATE TABLE IF NOT EXISTS Orders(OrderID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, ClientID CHAR(5), ProductID CHAR(5), Quantity INT, Cost DECIMAL(8,2), FOREIGN KEY (ClientID) REFERENCES Clients(ClientID));

CREATE TABLE IF NOT EXISTS Employees(EmployeeID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, FullName VARCHAR(100), JobTitle VARCHAR(100), County VARCHAR(100), LineManagerID INT);
